# 1.1.5.3 Ensure noexec option set on /var/log partition

- name: set var
  set_fact:
    task_name: "Ensure noexec option set on /var/log partition"
    task_id: "1.1.5.3"

- name: 1.1.5.3 Ensure noexec option set on /var/log partition
  shell: findmnt --kernel /var/log | grep noexec
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('noexec') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
