# 1.1.6.3 Ensure nodev option set on /var/log/audit partition

- name: set var
  set_fact:
    task_name: "Ensure nodev option set on /var/log/audit partition"
    task_id: "1.1.6.3"

- name: 1.1.6.3 Ensure nodev option set on /var/log/audit partition
  shell: findmnt --kernel /var/log/audit | grep nodev
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('nodev') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
