# 1.2.2 Ensure gpgcheck is globally activated

- name: set var
  set_fact:
    task_name: "Ensure gpgcheck is globally activated"
    task_id: "1.2.2"
 
- name: 1.2.2 Ensure gpgcheck is globally activated
  shell: grep ^gpgcheck /etc/dnf/dnf.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('gpgcheck=1') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
