# 1.2.3 Ensure package manager repositories are configured

- name: set var
  set_fact:
    task_name: "Ensure package manager repositories are configured"
    task_id: "1.2.3"
 
- name: 1.2.3 Ensure package manager repositories are configured
  shell: dnf repolist
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('repo id') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
