# 1.7.6 Ensure permissions on /etc/issue.net are configured

- name: set var
  set_fact:
    task_name: "Ensure permissions on /etc/issue.net are configured"
    task_id: "1.7.6"

- name: 1.7.6 Ensure permissions on /etc/issue.net are configured
  shell: stat -L /etc/issue.net
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: "'Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)' in grep_result.stdout"

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
