# 4.1.2 Ensure permissions on /etc/crontab are configured
- name: set var
  set_fact:
    task_name: "Ensure permissions on /etc/crontab are configured"
    task_id: "4.1.2"

- name: 4.1.2 Ensure permissions on /etc/crontab are configured
  shell:  stat /etc/crontab | grep 600
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('600') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
