# 5.1.2.1.1 Ensure systemd-journal-remote is installed
- name: set var
  set_fact:
    task_name: "Ensure systemd-journal-remote is installed"
    task_id: "5.1.2.1.1"

- name: 5.1.2.1.1 Ensure systemd-journal-remote is installed
  shell:  rpm -q systemd-journal-remote
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.rc == 0

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
